### ISSUE TITLE
class 'whole header' issues

### ISSUE THREAD

**Issue by e1eny** [e1eny/homework-8-elene-soso#3]
https://github.com/e1eny/homework-8-elene-soso/blob/438eea0c66ae88f56b1b43305ca195f789a24d22/css/style.css#L6
flex-direction: row ისედაც დეფაულთად არის row
alight-content: center არ მუშაობს
![Screenshot_11](https://user-images.githubusercontent.com/83778081/122689479-cda15700-d233-11eb-9520-44b9c3994f13.png)

**Comment by Ssosiashvili** [comment]
flex-direction არაფერს აშავებს ჩემი აზრით.
align-ს წავშლი.
ფოტო რო იწელება უნდა იწელებოდეს მგონი :ხ
